engines:
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR1,PSR2"
  phpmd:
      enabled: true
      config:
        file_extensions:
        - php
ratings:
  paths:
  - "backend/src/**.php"
exclude_paths:
- "frontend/**/*"
- "backend/web/*"
- "backend/composer.lock"
- "**/bin/**/*"
- "**/data/**/*"
- "**/features/**/*"
- "**/spec/**/*"
- "**/tests/**/*"
- "**/vendor/**/*"
- "configuration/**/*"
- "database/**/*"
- "**.json"
- "**.yml"
- "**.xml"
- "**.sh"
- "**.md"
- "LICENSE"