engines:
  phpcodesniffer:
    enabled: true
    config:
      standard: "PSR1,PSR2"
  phpmd:
      enabled: true
      config:
        file_extensions:
        - php
  duplication:
    enabled: true
    config:
      languages:
      - php:
      - javascript:
ratings:
  paths:
  - "backend/src/**.php"
exclude_paths:
- "frontend/**/*"
- "**/bin/**/*"
- "**/data/**/*"
- "**/spec/**/*"
- "**/tests/**/*"
- "**/vendor/**/*"