sudo: required
dist: trusty
language: php
php:
  - '7.1'
install:
  - cd backend && composer install && cd -
services:
  - docker
script:
  - cd backend && bin/phpspec run && cd -
  - cd backend && bin/phpunit && cd -
