version: "3" # Docker Swarm compatible
services:
  frontend:
    # replace username/repo:tag with your name and image details
    image: nginx:1.13
    deploy:
      replicas: 3 
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
  backend:
    # replace username/repo:tag with your name and image details
    image: php:7.1-apache
    deploy:
      replicas: 3 
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - webnet
  database:
    # replace username/repo:tag with your name and image details
    image: mysql:5.6
    deploy:
      #replicas: 1 
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "3306:3306"
    networks:
      - webnet
networks:
  webnet:


