# Minimum version required for Docker Swarm compatibility and configs feature
version: "3.3"

services:

# ▄████  █▄▄▄▄ ████▄    ▄     ▄▄▄▄▀ ▄███▄      ▄   ██▄
# █▀   ▀ █  ▄▀ █   █     █ ▀▀▀ █    █▀   ▀      █  █  █
# █▀▀    █▀▀▌  █   █ ██   █    █    ██▄▄    ██   █ █   █
# █      █  █  ▀████ █ █  █   █     █▄   ▄▀ █ █  █ █  █
#  █       █         █  █ █  ▀      ▀███▀   █  █ █ ███▀
#   ▀     ▀          █   ██                 █   ██

  # Front-end Angular JavaScript single page application
  frontend:
    image: nginx:1.13
    # Mount the frontend subdirectory of this project into /var/frontend in the container running Nginx
    volumes:
      - ./frontend:/var/frontend
    # Overwrite the default Nginx configuration (shortcut to avoid building a pre-configured image)
    configs:
      - source: frontend-nginx
        target: /etc/nginx/conf.d/default.conf
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 32M
      restart_policy:
        condition: on-failure
      # Normally you would use a container registry to store a fully built copy of your application, but since
      # we are mounting a local directory for demonstration purposes, restrict these containers from running
      # anywhere but on the Docker Swarm master (i.e. this computer, where the local directory exists)
      placement:
        constraints: [node.role == manager]
    # Forward port 80 (HTTP default) to port 80 in the containers
    ports:
      - "8888:80"
    networks:
      - default

# ███   ██   ▄█▄    █  █▀ ▄███▄      ▄   ██▄
# █  █  █ █  █▀ ▀▄  █▄█   █▀   ▀      █  █  █
# █ ▀ ▄ █▄▄█ █   ▀  █▀▄   ██▄▄    ██   █ █   █
# █  ▄▀ █  █ █▄  ▄▀ █  █  █▄   ▄▀ █ █  █ █  █
# ███      █ ▀███▀    █   ▀███▀   █  █ █ ███▀
#         █          ▀            █   ██
#        ▀

  # Back-end PHP REST API application
  backend:
    image: richarvey/nginx-php-fpm:1.2.1
    # Mount the backend subdirectory of this project into /var/backend in the container running Apache and mod-php
    volumes:
      - ./backend:/var/backend
    # Overwrite the default Nginx configuration (shortcut to avoid building a pre-configured image)
    configs:
      - source: backend-nginx
        target: /etc/nginx/sites-available/default.conf
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 64M
      restart_policy:
        condition: on-failure
      # Docker Swarm restriction, see notes above
      placement:
        constraints: [node.role == manager]
    # Forward port 9080 to port 80 (HTTP default) in the containers, must be listening on a different port to the
    # front-end containers because the Angular application is being served from port 80 on every Docker Swarm node,
    # therefore the Angular application will talk to the REST API using port 9080 in this demonstration. This is only
    # required in this case because we are re-using localhost to serve both applications.
    ports:
      - "9999:80"
    networks:
      - default

# ███   ██▄   ██▄
# █  █  █  █  █  █
# █ ▀ ▄ █   █ █   █
# █  ▄▀ █  █  █  █
# ███   ███▀  ███▀

  # Behavioural test runner
  testrunner:
    image: magickatt/behat-mink
    # Mount the backend subdirectory of this project into /var/backend in the container
    volumes:
        - ./backend:/var/backend
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 64M
      restart_policy:
        condition: on-failure
      # Docker Swarm restriction, see notes above
      placement:
        constraints: [node.role == manager]
    networks:
      - default

networks:
  default:

configs:
  frontend-nginx:
    file: ./configuration/frontend-nginx.conf
  backend-nginx:
    file: ./configuration/backend-nginx.conf
